---
title: "MOUTH analysis"
output: html_notebook
author: "Caitlin Halfacre"
---
Test notebook

```{r message=FALSE, warning=TRUE}
knitr::opts_chunk$set(echo = FALSE)
packages = c("dplyr","readr", "ggplot2", "rstatix", "ruler", "broom", "tidygam","tidymv", "mgcv", "itsadug",
             "doFuture","parallel",
             "ggforce","khroma","janitor","viridis","scales","colorspace","rcartocolor")
lapply(packages, library, character.only = TRUE)
options(pillar.sigfig = 4)
```


# Data and Setup
## Data
```{r data, message=FALSE, warning=FALSE}
my_seed = 1234

data_M_long <- read_csv("data_M_long.csv")

data_M_gamm <- data_M_long %>%
  mutate_if(is.character,as.factor) %>% 
  mutate(borough_ord = ordered(borough)) %>%
  mutate(groupgeog_ord = ordered(groupgeog)) %>%
  mutate(traj= factor(rowNumber_all)) %>%
  mutate(ID = factor(ID)) %>%
  mutate(lexSet_ord = ordered(lexSet)) %>%
  mutate(sex_ord = ordered(sex)) %>%
  mutate(age_ord = ordered(age)) %>%
  mutate(word_ord = ordered(word)) %>%
  mutate(folplc_ord = factor(ordered(plt_place))) %>%
  # mutate(percent = as.numeric(percent)) %>% 
  droplevels() %>%
  ungroup() %>%
  mutate(age_bor = ordered(interaction(age, borough)))

contrasts(data_M_gamm$age_ord) <- "contr.treatment"
contrasts(data_M_gamm$sex_ord) <- "contr.treatment"
contrasts(data_M_gamm$borough_ord) <- "contr.treatment"
contrasts(data_M_gamm$folplc_ord) <- "contr.treatment"
```

## themes
```{r themes, message=FALSE, warning=FALSE}
theme_Caitlin_transp <- function() {theme_bw(base_size = 12) %+replace%
    theme(plot.background  = element_rect(fill = "transparent", colour = NA),
          panel.background = element_rect(fill="gray90", colour=NA),
          legend.background = element_rect(fill="transparent", colour=NA),
          legend.key = element_rect(fill="transparent", colour=NA),
          panel.grid.major = element_line(colour = "white", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))}

theme_Caitlin <- function() {theme_bw(base_size = 12) %+replace%
    theme(panel.grid.major = element_line(size = 0.5, colour = "grey90"),
          panel.grid.minor = element_line(size = 0.2, colour = "grey70"))}


theme_Caitlin_present <- function() {theme_bw(base_size = 22) %+replace%
    theme(plot.background  = element_rect(fill = "transparent", colour = NA),
          panel.background = element_rect(fill="gray90", colour=NA),
          legend.background = element_rect(fill="transparent", colour=NA),
          legend.key = element_rect(fill="transparent", colour=NA),
          panel.grid.major = element_line(colour = "white", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))}

theme_Caitlin_gamm <- function() {theme_bw(base_size = 16) %+replace%
    theme(plot.background  = element_rect(fill = "transparent", colour = NA),
          panel.background = element_rect(fill="transparent", colour=NA),
          legend.background = element_rect(fill="transparent", colour=NA),
          legend.key = element_rect(fill="transparent", colour=NA),
          panel.grid.major = element_line(colour = "white", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))}

theme_Caitlin_gammpresent <- function() {theme_bw(base_size = 22) %+replace%
    theme(plot.background  = element_rect(fill = "transparent", colour = NA),
          panel.background = element_rect(fill="white", colour=NA),
          legend.background = element_rect(fill="transparent", colour=NA),
          legend.key = element_rect(fill="transparent", colour=NA),
          panel.grid.major = element_line(colour = "white", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))}

safe_pal_3 <- carto_pal(3, "Safe")
safe_pal_4 <- carto_pal(4, "Safe")
safe_pal_5 <- carto_pal(5, "Safe")
safe_pal_6 <- carto_pal(6, "Safe")
safe_pal_7 <- carto_pal(7, "Safe")
safe_pal_8 <- carto_pal(8, "Safe")
safe_pal_9 <- carto_pal(9, "Safe")
safe_pal_10 <- carto_pal(10, "Safe")
safe_pal_11 <- carto_pal(11, "Safe")
safe_pal_12 <- carto_pal(12, "Safe")
```
## Parallel
```{r parallel, message=TRUE, warning=FALSE}
all_cores <- availableCores()
registerDoFuture()
cl <- makeCluster(all_cores)
plan(cluster, workers = cl)
all_cores
```

# Mouth in all boroughs
## F2
```{r F2gamm1}
F2.gamm1 <- bam(F2 ~
                  borough_ord +
                  # age_ord +
                  # sex_ord +
                  # fol_seg_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4)
                  # s(percent, by=age_ord, k=4) +
                  # s(percent, by=sex_ord, k=4) +
                  # s(percent, by=fol_seg_ord, k = 4) +
                  # ti(percent, dur) + #interaction between shape and duration
                  # s(percent, ID, bs="fs", xt="cr",m=1,k=4) + #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                # s(percent, word, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm1output}
# check
gam.check(F2.gamm1)
# summary
summary(F2.gamm1)
```

```{r F2gamm2}
#least model + ID
F2.gamm2 <- bam(F2 ~
                  borough_ord +
                  # age_ord +
                  # sex_ord +
                  # fol_seg_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  # s(percent, by=age_ord, k=4)
                  # s(percent, by=sex_ord, k=4) +
                  # s(percent, by=fol_seg_ord, k = 4) +
                  # ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, word, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm2output}
# check
gam.check(F2.gamm2)
# summary
summary(F2.gamm2)
```

```{r}
compareML(F2.gamm1,F2.gamm2)
```

```{r F2gamm3}
#least model + ID + age
F2.gamm3 <- bam(F2 ~
                  borough_ord +
                  age_ord +
                  # sex_ord +
                  # fol_seg_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  s(percent, by=age_ord, k=4) +
                  # s(percent, by=sex_ord, k=4) +
                  # s(percent, by=fol_seg_ord, k = 4) +
                  # ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm3output}
# check
gam.check(F2.gamm3)
# summary
summary(F2.gamm3)
```

```{r compare 2vs3}
compareML(F2.gamm2,F2.gamm3)
```


```{r F2gamm4}
#least model + ID + age + sex
F2.gamm4 <- bam(F2 ~
                  borough_ord +
                  age_ord +
                  sex_ord +
                  # fol_seg_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  s(percent, by=age_ord, k=4) +
                  s(percent, by=sex_ord, k=4) +
                  # s(percent, by=fol_seg_ord, k = 4) +
                  # ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm4output}
# check
gam.check(F2.gamm4)
# summary
summary(F2.gamm4)
```

```{r}
compareML(F2.gamm3,F2.gamm4)
```

<!-- ```{r gamm4 predictions} -->
<!-- F2.gamm4.p <- tidymv::predict_gam(F2.gamm4 -->
<!--                           , exclude_terms = list( -->
<!--                             # "s(percent:folplc_ord" -->
<!--                             "s(percent:sex_ord" -->
<!--                             # ,"s(percent,ID)" -->
<!--                             # ,"s(percent,word)" -->
<!--                             # ,"ti(percent,dur)" -->
<!--                           ) -->
<!--                           , -->
<!--                           values = list( -->
<!--                             sex_ord = NULL -->
<!--                             # ,age_ord = NULL -->
<!--                             # ,folplc_ord = NULL -->
<!--                             ,ID = NULL -->
<!--                             # ,word = NULL -->
<!--                             # ,traj = NULL -->
<!--                             # ,dur = mean(data_M_gamm$dur) -->
<!--                           ) -->
<!--                           ) -->
<!-- ``` -->

```{r F2gamm5}
#least model + ID + age + sex + folplc_ord
F2.gamm5 <- bam(F2 ~
                  borough_ord +
                  age_ord +
                  sex_ord +
                  # folplc_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  s(percent, by=age_ord, k=4) +
                  s(percent, by=sex_ord, k=4) +
                  s(percent, by=folplc_ord, k = 4) +
                  # ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm5output}
# check
gam.check(F2.gamm5)
# summary
summary(F2.gamm5)
```

```{r compare4vs5}
compareML(F2.gamm4,F2.gamm5)
```

<!-- ```{r predictions5} -->
<!-- F2.gamm5.p <- tidymv::predict_gam(F2.gamm5 -->
<!--                           , exclude_terms = list( -->
<!--                             "s(percent:folplc_ord" -->
<!--                             # "s(percent:sex_ord" -->
<!--                             ,"s(percent,ID)" -->
<!--                             # ,"s(percent,word)" -->
<!--                             # ,"ti(percent,dur)" -->
<!--                           ) -->
<!--                           , -->
<!--                           values = list( -->
<!--                             # sex_ord = NULL -->
<!--                             # ,age_ord = NULL -->
<!--                             folplc_ord = NULL -->
<!--                             ,ID = NULL -->
<!--                             # ,word = NULL -->
<!--                             # ,traj = NULL -->
<!--                             # ,dur = mean(data_M_gamm$dur) -->
<!--                           ) -->
<!--                           ) -->
<!-- ``` -->


```{r F2gamm6}
#least model + ID + age + sex + folplc_ord + ti(dur)
F2.gamm6 <- bam(F2 ~
                  borough_ord +
                  age_ord +
                  sex_ord +
                  # folplc_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  s(percent, by=age_ord, k=4) +
                  s(percent, by=sex_ord, k=4) +
                  s(percent, by=folplc_ord, k = 4) +
                  ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) #random smooth
                  # s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm6output}
# check
gam.check(F2.gamm6)
# summary
summary(F2.gamm6)
```

```{r}
compareML(F2.gamm5,F2.gamm6)
```
```{r F2gamm7}
#least model + ID + age + sex + folplc_ord + ti(dur) + traj
F2.gamm7 <- bam(F2 ~
                  borough_ord +
                  age_ord +
                  sex_ord +
                  folplc_ord +
                  s(percent, k=4) + #difference in height of traj
                  s(percent, by=borough_ord, k = 4) +
                  s(percent, by=age_ord, k=4) +
                  s(percent, by=sex_ord, k=4) +
                  s(percent, by=folplc_ord, k = 4) +
                  ti(percent, dur) + #interaction between shape and duration
                  s(percent, ID, bs="fs", xt="cr",m=1,k=4) + #random smooth
                  s(percent, traj, bs="fs", xt="cr",m=1,k=4) #random smooth
                , data=data_M_gamm,method="fREML", nthreads = all_cores)
```

```{r F2 gamm7output}
# check
gam.check(F2.gamm7)
# summary
summary(F2.gamm7)
```

```{r compare6vs7}
compareML(F2.gamm6,F2.gamm7)
```

```{r predictions6}
F2.gamm7.p <- tidymv::predict_gam(F2.gamm7
                          , exclude_terms = list(
                            "s(percent:folplc_ord"
                            ,"s(percent:sex_ord"
                            ,"s(percent,ID)"
                            ,"ti(percent,dur)"
                          )
                          ,
                          values = list(
                            sex_ord = NULL
                            ,folplc_ord = NULL
                            ,ID = NULL
                            ,traj = NULL
                            ,dur = mean(data_M_gamm$dur)
                          )
                          )
write_csv(F2.gamm7.p, "F2-gamm7-p.csv")
```

###################################################
```{r F2gamm1plot}
#### plot ####
F2.gamm7.plot <- ggplot(data = F2.gamm7.p,
                        aes(
                          x=percent,
                          y=fit
                          ,linecolour = borough_ord
                          # ,fill = borough_ord
                          # ,line = "solid"
                        ))+
  theme_Caitlin_gamm()+
  geom_smooth_ci(borough_ord)+
  scale_y_continuous(position = "right",
                  limits = c(800,2000),
                  breaks = seq(0, 2000, 200)
                  )+
  # scale_linetype_manual(values=c("solid","dotted"), name = "Lexical Set", labels = c("HOPE","HOLE"))+
  # scale_color_manual(values=c(hopecol,holecol),name="Lexical Set", labels = c("HOPE","HOLE"))+
  facet_wrap(~age_ord)+
  NULL
F2.gamm7.plot
```